In [1]:
# Ejercicio
# Considere los datos siguientes, que corresponden a estadísticas de accidentes en una empresa para tres áreas durante cuatro
# años: ver PPT

import numpy as np
accidentes = np.array ([[0,1,1],
                      [1,0,1],
                      [1,3,2],
                      [2,2,0]])

In [2]:
# Problema 1: Mediante el uso de un arreglo de NumPy determine:
 # a) El número total de accidentes durante los cuatro años
    
accidentes.sum()

14

In [3]:
# Problema 2: El número total de accidentes por área (por columna)

accide_areas = accidentes.sum(axis=0)
accide_areas

array([4, 6, 4])

In [4]:
# Resultados mejor presentados
print ("Los accidentes del área 1: ", accide_areas[0])
print ("Los accidentes del área 2: ", accide_areas[1])
print ("Los accidentes del área 3: ", accide_areas[2])

Los accidentes del área 1:  4
Los accidentes del área 2:  6
Los accidentes del área 3:  4


In [5]:
# Problema 3: El número total de accidentes por año (por renglón)

accid_anios = accidentes.sum(axis=1)
accid_anios

array([2, 2, 6, 4])

In [6]:
# conservación de dimensiones (mantener la misma orientación)

accid_anios = accidentes.sum(axis=1, keepdims= True)
accid_anios

array([[2],
       [2],
       [6],
       [4]])

In [7]:
print ("Los accidentes del año 1", accid_anios[0])
print ("Los accidentes del año 2", accid_anios[1])
print ("Los accidentes del año 3", accid_anios[2])
print ("Los accidentes del año 4", accid_anios[3])

Los accidentes del año 1 [2]
Los accidentes del año 2 [2]
Los accidentes del año 3 [6]
Los accidentes del año 4 [4]


In [8]:
# problema 4: El número máximo y mínimo de accidentes por área y año

maximo = accidentes.max()
minimo = accidentes.min()
print(f"Máximo de accidentes: {maximo}")
print(f"Mínimo de accidentes: {minimo}")

Máximo de accidentes: 3
Mínimo de accidentes: 0


In [9]:
# Problema 5: El número promedio de accidentes por área y año
promedio = accidentes.mean()
print(f"Promedio de accidentes: {promedio} ")

Promedio de accidentes: 1.1666666666666667 


In [2]:
# Determine la suma descrita en la imagen de abajo mediante:
 # a) Un ciclo en Python
 # b) Una función vectorizada de NumPy : ver PPT

arreglo = np.array([[1,2,3],
                   [4,5,6]])
dimensiones = arreglo.shape
print(dimensiones[0]) # de renglones
print(dimensiones[1]) # de columnas
print (arreglo [0][0])

2
3
1


In [6]:
 # a) Un ciclo en Python
import time
inicio = time.time()

arreglo_final = np.zeros((2,3))
for renglon in range (dimensiones[0]):
    for columna in range (dimensiones [1]):
        arreglo_final[renglon][columna] = arreglo [renglon] [columna] + 3
print(arreglo_final)

fin = time.time()
print ("Tiempo total de ejecución (segs.)", fin -inicio)

[[4. 5. 6.]
 [7. 8. 9.]]
Tiempo total de ejecución (segs.) 0.0010025501251220703


In [7]:
 # b) Una función vectorizada de NumPy

import time
inicio = time.time()

arreglo_final = arreglo + 3
print(arreglo_final)

fin = time.time()
print ("Tiempo total de ejecución (segs.)", fin -inicio) # el tiempo es menor cuando se usa una función vectorizada
    

[[4 5 6]
 [7 8 9]]
Tiempo total de ejecución (segs.) 0.001001119613647461


In [8]:
# Broadcasting de un escalar

arreglo_prod= arreglo*3
arreglo_prod

array([[ 3,  6,  9],
       [12, 15, 18]])

In [9]:
# evaluación de condiciones
arreglo1= np.array([[1,2,3],
                   [4,5,6]])
arreglo>2

array([[False, False,  True],
       [ True,  True,  True]])

In [10]:
# las funciones de Python no están vectorizadas de origen
arreglo= np.array(["NumPy", "Maneja", "vectorización"])
len(arreglo)>5

False

In [11]:
# Transformación para vectorización de función len
len_vectorizada= np.vectorize(len)
len_vectorizada(arreglo) > 5

array([False,  True,  True])

In [12]:
# Broadcasting de renglones
arreglo = np.arange(10).reshape((2,5))
arreglo

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
arreglo + np.array([0,1,2,3,4])

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [15]:
# Broadcasting de columnas
arreglo = np.arange(10).reshape((2,5))
arreglo + np.array([0,1]).reshape((2,1))

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [16]:
arreglo + np.array([0,1])

ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

In [18]:
# Volteo a un arreglo
arreglo = np.array([[1.1,1.2,1.3],
                   [2.1,2.2,2.3],
                   [4.1,4.2,4.3]])
np.flip(arreglo)

array([[4.3, 4.2, 4.1],
       [2.3, 2.2, 2.1],
       [1.3, 1.2, 1.1]])

In [19]:
# Transposición de un arreglo
arreglo = np.array([[1.1,1.2,1.3],
                   [2.1,2.2,2.3],
                   [4.1,4.2,4.3]])
np.transpose(arreglo)

array([[1.1, 2.1, 4.1],
       [1.2, 2.2, 4.2],
       [1.3, 2.3, 4.3]])

In [20]:
# ejercicio 

# Implemente las siguientes operaciones en Python con NumPy. ¿Qué tipo de operación de “Broadcasting” se está realizando en
# cada caso?

# operación 1
np.array([[1,2], [3,4]]) * np.array([[5] , [10]])

array([[ 5, 10],
       [30, 40]])

In [21]:
# operación 2
np.array([[1,2], [3,4]]) - np.array([[5, 10]])

array([[-4, -8],
       [-2, -6]])