In [1]:
import numpy as np


In [3]:
# Creación de un arreglo unidimensional a partir de una lista

lista1=[1,2,3,4,5]
arreglo= np.array(lista1)
arreglo

array([1, 2, 3, 4, 5])

In [4]:
type(arreglo)

numpy.ndarray

In [5]:
# Creación de un arreglo a partir de una lista (bidimensional)
lista2=[[1,2,3],
       [4,5,6],
       [7,8,9]]
arreglo2 = np.array(lista2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# las listas pueden contener diversos tipos de datos
lista= ["A", True, 1]
lista

['A', True, 1]

In [7]:
# Los arreglos solo pueden tener un mismo tipo de datos
# Usan menos espacio en memoria

arreglo=np.array(lista)
arreglo #Sólo se almacenan textos

array(['A', 'True', '1'], dtype='<U11')

In [11]:
# Creación de arreglos con ceros
arreglo3 = np.zeros((5,4))
arreglo3
# este ejemplo se puede usar para machine learning, meter matrices para posteriormente ser modificadas

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# Creación de arreglo con números aleatorios uniformes entre 0 y 1
np.random.random((3,2))
# este ejemplo puede funcionar para modelos de simulación 

array([[0.21373958, 0.12113622],
       [0.4004287 , 0.05744102],
       [0.81017929, 0.31023255]])

In [14]:
# Creación de arreglos en un rango
np.arange(-2,7)

array([-2, -1,  0,  1,  2,  3,  4,  5,  6])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
# Ejercicio 1 Mediante el uso de la librería NumPy desarrolle un código en Python que sea capaz de crear el arreglo
# Tri-dimensional siguiente: ver ppt

arreglo1= np.array([[1,2],
                    [5,7]])
arreglo2= np.array([[8,9],
                    [5,7]])
arreglo3= np.array([[1,2],
                    [5,7]])

In [19]:
arreglo3D = np.array([arreglo1,arreglo2,arreglo3])
arreglo3D

array([[[1, 2],
        [5, 7]],

       [[8, 9],
        [5, 7]],

       [[1, 2],
        [5, 7]]])

In [20]:
arreglo3 = np.zeros((5,4))
arreglo3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
arreglo3.shape

(5, 4)

In [27]:
# Conversión de un arreglo multi-dimensional a uni-dimensional
lista2= [[1,2,3],
        [4,5,6],
        [7,8,9]]
arreglo2= np.array(lista2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arreglo2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# Cambio de dimensión de un arreglo
arreglo= np.array([[1,2],
                 [3,4],
                 [5,6]])
arreglo.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# Ejemplo de error en el ejemplo anterior al querer poner una columna nueva en el reshape (cambiar la dimensión)
arreglo.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [30]:
# el atributo dtype
np.array([1.25,2.43,200.88]).dtype

dtype('float64')

In [31]:
arreglo_int= np.array([[1,2,3] , [4,5,6]])
arreglo_int.dtype

dtype('int32')

In [32]:
arreglo_string = np.array(["Introducción", "a", "la", "programación"])
arreglo_string.dtype

dtype('<U12')

In [33]:
# Uso de type como argumento
arreglo= np.array([1.25,2.43,200.88], dtype = np.float32)  # mismo arreglo de arriba
arreglo.dtype

dtype('float32')

In [34]:
# Cambio de tipo de arreglo
arreglo_boleano = np.array([[True, False]], dtype = np.bool_)
arreglo_boleano.dtype

dtype('bool')

In [36]:
arreglo = arreglo_boleano.astype(np.int32)
arreglo

array([[1, 0]])

In [37]:
# Homologación del tupo por jerarquía
np.array ([0, 50,50.8]).dtype

dtype('float64')

In [40]:
np.array ([False,42])

array([ 0, 42])