In [1]:
import numpy as np

In [3]:
# Indexación de un solo elemento
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Extracción de elementos en forma ascendente
x[2]

2

In [5]:
# Extracción de elementos en forma descendente
x[-2]

8

In [6]:
# Conversión del arreglo a formato bidimensional
x.shape=(2,5)
x


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
# Extracción del elemento con índice 1 en el renglón e indice 3 en columna
x[1,3]

8

In [11]:
# Alternativa de extracción del elemento con índice 1 en el renglón e índice 3 en columna
x[1][3]

8

In [12]:
# Extracción del elemento con índice 1 en renglón y primer elemento en forma descendente 
x[1,-1]

9

In [13]:
# Extracción del renglón completo con indice 0 (al no especificar índice de columna)
x[0]

array([0, 1, 2, 3, 4])

In [15]:
# Cortes en arreglos
x = np.array ([0,1,2,3,4,5,6,7,8,9])
x[1:7:2] # este resultado corresponde al formato "start:stop:step"

array([1, 3, 5])

In [16]:
# Corte del arreglo de adelante hacia atrás, considerando dos elementos
x[-2:10]

array([8, 9])

In [17]:
# Corte del arreglo de adelante hacía atrás, iniciando tres posiciones a partir del final y retrocediendo en 3
# Hasta tener en límite el número 3

x[-3:3:-1]

array([7, 6, 5, 4])

In [22]:
# Definición de un nuevo arreglo 
# Creación de un arreglo en forma descendente - Del 10 al 1 (sin incluirlo)- con decrementos

x=np.arange(10,1,-1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [23]:
# extracción de elementos específicos del arreglo 
x[np.array([3,3,1,8])] #extracción de elementos con índices 3,3,1,8

array([7, 7, 9, 2])

In [24]:
# extracción de elementos con índices 3,3,-3 (descendente) y 8
x[np.array([3,3,-3,8])]

array([7, 7, 4, 2])

In [30]:
# Extracción basada en pares
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [33]:
# Extracción de "coordenadas" (0,0) , (2,1) y (4,2)
y[np.array([0,2,4]), np.array([0,1,2])]


array([ 0, 15, 30])

# UNIÓN DE ARREGLOS

In [34]:
# Concatenación de vectores
arr= np.concatenate(([1,2,3] , [4,5,6]))
arr

array([1, 2, 3, 4, 5, 6])

In [35]:
# Apilado verticar de vectores
np.stack(([1,2,3], [4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# Concatenación de Matrices
mat_1 = np.array([[1,2,3] , [4,5,6]])
mat_2 = np.array([[1,1,1] , [2,2,2]])
np.concatenate((mat_1, mat_2), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [38]:
np.concatenate((mat_1, mat_2), axis=1)

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 2, 2, 2]])

In [39]:
np.concatenate((mat_1, mat_2), axis=None) #vector unidimensional

array([1, 2, 3, 4, 5, 6, 1, 1, 1, 2, 2, 2])